
MAX_LOAD = 1200
DAY = 30
BASIC_INCOME = 1000
WATER_WEIGHT_PERCASE = 2
FOOD_WEIGHT_PERCASE = 3
WATER_PRICE_PERCASE = 5
FOOD_PRICE_PERCASE = 10
BASIC_WATER_CONSUMPTION_0 = 3
BASIC_FOOD_CONSUMPTION_0 = 4
BASIC_WATER_CONSUMPTION_1 = 9
BASIC_FOOD_CONSUMPTION_1 = 9
BASIC_WATER_CONSUMPTION_2 = 10
BASIC_FOOD_CONSUMPTION_2 = 10
END_NOTE = 25
